### ISSUE TITLE
Does String Make Smaller?

### ISSUE THREAD

**Issue by amark** [xem/miniDrawLoop#1]
Does this shrink it, @xem?

```
w = top
e = 'onmouse'
w[e+'up']=e=>...
```
?

https://github.com/xem/miniDrawLoop/blob/72a51d383524b27e45075d78c89c0336cfc380a3/index.html#L27-L33

**Comment by xem** [comment]
Sorry, it doesn't:

"w[e+'up']" is as long as "onmouseup"
